In [32]:
import pandas as pd
import sqlite3

conn = sqlite3.connect('/home/blueberry/project/data/db/bank.db')

with open('/home/blueberry/project/src/queries.sql', 'r') as sql_file:
    sql_sript = sql_file.read()

cursor = conn.cursor()

conn.commit()

In [35]:
df1 = pd.read_csv('/home/blueberry/project/data/db/raw/BankTransaction.csv')
df1.head()

   id  customer_id  amount operation_type
0   1            1     500        deposit
1   2            1     200        deposit
2   3            2     100        deposit
3   4            2      50       withdraw
4   5            3     300        deposit

In [36]:
df2 = pd.read_csv('/home/blueberry/project/data/db/raw/BankCustomerData.csv')
df2.head()

ParserError: Error tokenizing data. C error: Expected 18 fields in line 80, saw 26

In [37]:
df3 = pd.read_sql_query('SELECT * FROM customers', conn)
df3

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,term_deposit
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42634,21,student,single,secondary,no,2488,no,no,telephone,12,jan,661,2,92,1,success,yes
42635,87,retired,married,primary,no,2190,no,no,telephone,12,jan,512,2,-1,0,unknown,yes
42636,34,blue-collar,married,primary,no,6718,no,no,cellular,13,jan,278,4,97,1,other,no
42637,22,student,single,secondary,no,254,no,no,cellular,13,jan,143,2,-1,0,unknown,yes
42638,32,management,single,tertiary,no,1962,no,no,cellular,13,jan,130,1,-1,0,unknown,no

In [38]:
query = """
SELECT * FROM customers
"""

df_task = pd.read_sql_query(query, conn)
df_task

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,term_deposit
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42634,21,student,single,secondary,no,2488,no,no,telephone,12,jan,661,2,92,1,success,yes
42635,87,retired,married,primary,no,2190,no,no,telephone,12,jan,512,2,-1,0,unknown,yes
42636,34,blue-collar,married,primary,no,6718,no,no,cellular,13,jan,278,4,97,1,other,no
42637,22,student,single,secondary,no,254,no,no,cellular,13,jan,143,2,-1,0,unknown,yes
42638,32,management,single,tertiary,no,1962,no,no,cellular,13,jan,130,1,-1,0,unknown,no

In [40]:
curr = conn.cursor()
query = """
SELECT 
    c.id, 
    c.full_name, 
    o.amount, 
    o.date
FROM customers c
JOIN operations o ON c.id = o.customer_id
"""
df_joined = pd.read_sql_query(query, conn)

DatabaseError: Execution failed on sql '
SELECT
    c.id,
    c.full_name,
    o.amount,
    o.date
FROM customers c
JOIN operations o ON c.id = o.customer_id
': no such column: c.id